defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

predictions_path: ../../sample_predictions/0.parquet
evaluation_output_dir: ../../sample_output

hydra:
  output_subdir: null
  run:
    dir: .
